<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Anggota extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('anggota')->insert([
            [
                'name' => 'Abie Nur Budi Pangestiko',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Ketua',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Tedi Fatur Rohman',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Wakil Ketua',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Junaidi Rio Syamsudin',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Sekretaris 1',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Neza Firsty Ananda',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Sekretaris 2',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Reynaldi Surya Satria',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Bendahara 1',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Adam Amirul Insan Subroto',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Bendahara 2',
                'divisi_id' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Muhammad Surya Duta Al-Amin',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Abya Bahari Wafdulloh S',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Mayang Angelina',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Amandatul Mauliya Agustina',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Eclesianetha Ayu Pasha',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Zulia Nur Farida',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Nola Rahma Alhamda',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Muhammad Ilhamsyah Asyari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Ajeng Nur Putri Rahayu',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Atika Dwi Lestari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Dayegha Feruziarya Putri Abelgissabella',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Deraya Shasa Isyaka',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Tasya Putri Abidtya',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Zayyan Nuri Hidayati',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Feriska Nofita Ramadhani',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Akbar Ali Arbai',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Della Aprillia Sari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Vanessa Wida Anggraeni',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Willy Harisyah Putra',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Yunda Amelia Putri',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'M Rasyid Abdul Zacky',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Muhammad Fajar Wahyu Pratama',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Diana Saputri',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Moch. Bagas Asrofi',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Ferdina Oktaviani Putri',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Rania Insyira Munawar',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Riski Slamet Hartanto',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Surya Adi Winata Fatah',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Tedy Wijaya',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Muhammad Wahyu Afandi',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Giza Fatimatus Ghiffania',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Amrina Shalsabila Dzaktrin Al Arasyi',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Dimas Tri Kurniawan',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Ficha Adeliana',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Nadia Neila Rosyida',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Rara Ratu Pingkan Fransiska',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Yosua Putra Marsando',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Hernanda Bagus Hanafi',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'Chief Operating',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Aisyah Mawadah Warohmah',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Aulia Putri Wulandari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Fatimah Nur Nisa',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Silvia Devitasari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Silvia Cantrika Sari',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Muhammad Abu Al Khoir Zaki Badawi',
                'email' => null,
                'phone' => null,
                'fakultas' => null,
                'prodi' => null,
                'semester' => null,
                'jabatan' => 'anggota',
                'divisi_id' => 6,
                'status' => 'active',
            ],
        ]);
    }
}
